[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "Return"
mods = "Super|Shift"

[general]
live_config_reload = true

[font]
normal = {family = "CaskaydiaMono Nerd Font", style = "Regular"} 

[colors.bright]
black = "#42505D"
blue = "#5EC4FF"
cyan = "#70E1E8"
green = "#8BD49C"
magenta = "#E27E8D"
red = "#DA5368"
white = "#FFFFFF"
yellow = "#EBBF83"

[colors.normal]
black = "#333F4A"
blue = "#529AFC"
cyan = "#70E1E8"
green = "#8BD49C"
magenta = "#B62D65"
red = "#DA5368"
white = "#B7C5D3"
yellow = "#EBBF83"

[colors.primary]
background = "#171d23"
foreground = "#ffffff"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[window]
dynamic_title = true
title = "Terminal - Alacritty"
opacity = 0.65
blur = true

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 10
y = 10

[keyboard]
