# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = Noto Serif Test 

general {
    hide_cursor = true
    # grace = 5
    ignore_empty_input = true
    immediate_render = true
}

# uncomment to enable fingerprint authentication
auth {
    fingerprint {
        enabled = true
        ready_message = Scan fingerprint
        present_message = Scanning...
        retry_delay = 200 # in milliseconds
    }
}

animations {
    enabled = false
    bezier = linear, 0.33, 0.59, 0.66, 0.41
    animation = fadeIn, 1, 10, linear
    animation = fadeOut, 1, 10, linear
    animation = inputFieldDots, 1, 3, linear
}

background {
    monitor =
    # path = /home/bozic/Pictures/wallpapers/backiee-269161-landscape-1920x1080-upscaled.png
    path = /home/bozic/Pictures/hyprpaper/curvy-d.png
    blur_passes = 1
}

input-field {
    monitor =
    size = 23%, 6%
    outline_thickness = 5
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color =  rgba(d4cfcede)
    check_color = rgba(d4cfcede)
    fail_color = rgba(ff6633ee) rgba(ff0066ee) 40deg

    font_color = rgb(d4cfce)
    fade_on_empty = true
    rounding = 15

    font_family = $font
    placeholder_text = password
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    # dots_text_format = *
    # dots_size = 0.4
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, -20
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME # ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#variable-substitution
    font_size = 200
    font_family = $font
    color = rgb(d4cfce)

    position = 0, -40
    halign = center
    valign = top
}

# DATE
label {
    monitor =
    text = cmd[update:120000] date +"%A, %d %B %Y" # update every 120 seconds
    font_size = 40
    font_family = $font
    color = rgb(d4cfce)

    position = 0, 20
    halign = center
    valign = bottom
}

