# Hyprlauncher config
general {
    # font_size = 20
}
font_size = 20
# Finder settings
finders {
    # Enable/disable finders
    desktop_icons = true    
    # math_enabled = true
    # unicode_enabled = true
    
    # Custom prefixes
    # math_prefix = >
    # unicode_prefix = ":"
}

# Window settings
ui {
    window_size = 800 400

    
}
