# preload = /home/bozic/Pictures/wallpapers/CONTROL/wallpaper.jpg
# wallpaper = /home/bozic/Pictures/wallpapers/CONTROL/wallpaper.jpg
# preload = /home/bozic/Pictures/hyprpaper/pyramid.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/pyramid.png


# preload = /home/bozic/Pictures/hyprpaper/gottaMakeAMoveToATownThatsRightForMe.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/gottaMakeAMoveToATownThatsRightForMe.png

# preload = /home/bozic/Pictures/hyprpaper/macbook-1500x1000-upscaled.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/macbook-1500x1000-upscaled.png

preload = /home/bozic/Pictures/hyprpaper/john-anselmo_unsplash.jpg
wallpaper = , /home/bozic/Pictures/hyprpaper/john-anselmo_unsplash.jpg

# preload = /home/bozic/Pictures/hyprpaper/Windows-11-Abstract-Dark-Blue-Bloom-4K-Wallpaper.jpg
# wallpaper = , /home/bozic/Pictures/hyprpaper/Windows-11-Abstract-Dark-Blue-Bloom-4K-Wallpaper.jpg
