ipc = on
splash = true


wallpaper {
    monitor = 
    path = /home/bozic/Pictures/hyprpaper/pyramid.png
    fit_mode = cover
}

# THE BOARD
preload = /home/bozic/Pictures/hyprpaper/pyramid.png
wallpaper = DP-2, /home/bozic/Pictures/hyprpaper/pyramid.png

# CONTROL
# preload = /home/bozic/Pictures/hyprpaper/wallpaper.jpg
# wallpaper = , /home/bozic/Pictures/hyprpaper/wallpaper.jpg

# THE BOARD - DARK
# preload = /home/bozic/Pictures/hyprpaper/wallpaper02.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/wallpaper02.png

# NZXT CHINCHILLA
# preload = /home/bozic/Pictures/hyprpaper/gottamakeamovetoatownthatsrightforme.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/gottamakeamovetoatownthatsrightforme.png

# DAFT PUNK SOMETHING
# preload = /home/bozic/Pictures/hyprpaper/daft_punk_reference.jpg
# wallpaper = , /home/bozic/Pictures/hyprpaper/daft_punk_reference.jpg

# LAKE
# preload = /home/bozic/Pictures/hyprpaper/lake.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/lake.png 

# MACBOOK
# preload = /home/bozic/Pictures/hyprpaper/macbook-1500x1000-upscaled.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/macbook-1500x1000-upscaled.png

# GNOME
# preload = /home/bozic/Pictures/hyprpaper/curvy-d.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/curvy-d.png

# CLASSIC
# preload = /home/bozic/Pictures/hyprpaper/john-anselmo_unsplash.jpg
# wallpaper = , /home/bozic/Pictures/hyprpaper/john-anselmo_unsplash.jpg

# VALLEY
# preload = /home/bozic/Pictures/wallpapers/clemence-bergougnoux-EE1B5Kvu6yg-unsplash.jpg
# wallpaper = , /home/bozic/Pictures/wallpapers/clemence-bergougnoux-EE1B5Kvu6yg-unsplash.jpg

# WHITE DUNES
# preload = /home/bozic/Pictures/hyprpaper/pawel-czerwinski-unsplash.jpg
# wallpaper = , /home/bozic/Pictures/hyprpaper/pawel-czerwinski-unsplash.jpg

# SUNSET MOUNTAIN
# preload = /home/bozic/Pictures/hyprpaper/sebastien-lavalaye-rua4yqfqoc4-unsplash.jpg
# wallpaper = , /home/bozic/Pictures/hyprpaper/sebastien-lavalaye-rua4yqfqoc4-unsplash.jpg

# BRAZIL CLOUDS
# preload = /home/bozic/Pictures/hyprpaper/IMG_20250722_112340.jpg
# wallpaper = , /home/bozic/Pictures/hyprpaper/IMG_20250722_112340.jpg

# STONE FLOOR
# preload = /home/bozic/Pictures/hyprpaper/karsten-winegeart-8nan1obxruc-unsplash.jpg
# wallpaper = , /home/bozic/Pictures/hyprpaper/karsten-winegeart-8nan1obxruc-unsplash.jpg

# MOUNTAIN
# preload = /home/bozic/Pictures/wallpapers/mountain-8000x4484-upscaled.png
# wallpaper = , /home/bozic/Pictures/wallpapers/mountain-8000x4484-upscaled.png

# WINDOWS
# preload = /home/bozic/Pictures/hyprpaper/windows-11-abstract-dark-blue-bloom-4k-wallpaper.jpg
# wallpaper = , /home/bozic/Pictures/hyprpaper/windows-11-abstract-dark-blue-bloom-4k-wallpaper.jpg

# SNOWY MOUNTAIN
# preload = /home/bozic/Pictures/wallpapers/marek-piwnicki-UDrhbSiXh8M-unsplash.jpg
# wallpaper = , /home/bozic/Pictures/wallpapers/marek-piwnicki-UDrhbSiXh8M-unsplash.jpg

# preload = /home/bozic/Pictures/hyprpaper/gradient pink-red.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/gradient pink-red.png

# POP OS
# preload = /home/bozic/Pictures/hyprpaper/fnau0cexi86d1.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/fnau0cexi86d1.png

# MIKU
# preload = /home/bozic/Pictures/hyprpaper/miku.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/miku.png

# MIKU 2
# preload = /home/bozic/Pictures/hyprpaper/the-world-is-mine-cropped.png
# wallpaper = , /home/bozic/Pictures/hyprpaper/the-world-is-mine-cropped.png

# NEIN
# preload = /home/bozic/Pictures/hyprpaper/(76).png
# wallpaper = , /home/bozic/Pictures/hyprpaper/(76).png
