$animations = yes
$decorations = yes
$rounding = 10
$gaps_out = 8
$border_size = 1
# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 4
    gaps_out = $gaps_out # 8

    border_size = $border_size # 3

    # https://wiki.hyprland.org/Configuring/Variables/#variable-types for info about colors
    col.active_border = rgba(ffffffff) 
    # col.inactive_border = rgba(ccccff77) rgba(ddddff2a) rgba(ffffff20) rgba(ffffff69) 33deg
    # col.active_border = rgba(ccccffda) rgba(ddddffc3) rgba(ffffff48) rgba(ffffffa8) 33deg
    # col.inactive_border = rgba(2d68d088)

    # Set to true enable resizing windows by clicking and dragging on borders and gaps
    resize_on_border = false

    # Please see https://wiki.hyprland.org/Configuring/Tearing/ before you turn this on
    allow_tearing = false

    layout = dwindle
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = $rounding # 16
    rounding_power = 4 # 4

    # Change transparency of focused and unfocused windows
    active_opacity = 1
    inactive_opacity = 1# 0.93

    shadow {
        enabled = $decorations
        range = 12
        render_power = 2
        color = rgba(1a1a1ab8)
    }

    # https://wiki.hyprland.org/Configuring/Variables/#blur
    blur {
        enabled = $decorations
        size = 5
        passes = 3

        vibrancy = 0.9

        new_optimizations = true

        popups = true

        ignore_opacity = true
    }
}

# https://wiki.hyprland.org/Configuring/Variables/#animations
animations {
    enabled = $animations, yes please:)

    bezier = myBezier, 0.05, 0.9, 0.1, 1.05

    animation = windows, 1, 7, myBezier
    animation = windowsOut, 1, 7, default, popin 80%
    bezier = wind, 0.05, 0.9, 0.1, 1.05
    bezier = winIn, 0.1, 1.1, 0.1, 1.1
    bezier = winOut, 0.3, -0.3, 0, 1
    bezier = liner, 1, 1, 1, 1
    animation = windowsIn, 1, 6, winIn, slide
    animation = windowsMove, 1, 5, wind, slide
    animation = fade, 1, 10, default
    animation = workspaces, 1, 5, wind
}

# See https://wiki.hyprland.org/Configuring/Dwindle-Layout/ for more
dwindle {
    pseudotile = true # Master switch for pseudotiling.
    preserve_split = true # You probably want this
}

# See https://wiki.hyprland.org/Configuring/Master-Layout/ for more
master {
    new_status = master
}

